### ISSUE TITLE
test run sample data failed

### ISSUE THREAD

**Issue by weiyilan** [SynxFlow/SynxFlow#1]
PS C:\Users\weiyilan> & d:/Users/weiyilan/miniconda3/envs/py310/python.exe c:/Users/weiyilan/Desktop/synx/main.py
['DEM.gz', 'landcover.gz', 'rain_mask.gz', 'rain_source.csv']
C:\Users\weiyilan\Desktop\synx\flood_case
Traceback (most recent call last):
  File "c:\Users\weiyilan\Desktop\synx\main.py", line 26, in <module>
    case_input = IO.InputModel(DEM, num_of_sections=ngpus, case_folder=case_folder)
  File "D:\Users\weiyilan\miniconda3\envs\py310\lib\site-packages\synxflow-0.0.4.0-py3.10-win-amd64.egg\synxflow\IO\InputModel.py", line 137, in __init__
    self.set_rainfall()
  File "D:\Users\weiyilan\miniconda3\envs\py310\lib\site-packages\synxflow-0.0.4.0-py3.10-win-amd64.egg\synxflow\IO\InputModel.py", line 299, in set_rainfall
    self.Rainfall = Rainfall(self.attributes['precipitation_mask'],
  File "D:\Users\weiyilan\miniconda3\envs\py310\lib\site-packages\synxflow-0.0.4.0-py3.10-win-amd64.egg\synxflow\IO\Rainfall.py", line 56, in __init__
    self.set_source(rain_source, source_sep)
  File "D:\Users\weiyilan\miniconda3\envs\py310\lib\site-packages\synxflow-0.0.4.0-py3.10-win-amd64.egg\synxflow\IO\Rainfall.py", line 101, in set_source
    self.get_attrs()
  File "D:\Users\weiyilan\miniconda3\envs\py310\lib\site-packages\synxflow-0.0.4.0-py3.10-win-amd64.egg\synxflow\IO\Rainfall.py", line 201, in get_attrs
    spatial_res = np.sqrt(mode_value[0][0])*cellsize
IndexError: invalid index to scalar variable.

**Comment by weiyilan** [comment]
the code I am running is copied from github: "from synxflow import IO
import os
import matplotlib.pyplot as plt
import pandas as pd

from synxflow.IO.demo_functions import get_sample_data
dem_file, demo_data, data_path = get_sample_data() # get the path of sample data

print(os.listdir(data_path))
DEM = IO.Raster(os.path.join(data_path,'DEM.gz')) # load the file into a Raster object
DEM.mapshow() # plot the Raster object
plt.show()
rain_mask = IO.Raster(os.path.join(data_path,'rain_mask.gz'))
rain_mask.mapshow()
plt.show()
rain_source = pd.read_csv(os.path.join(data_path,'rain_source.csv'), header = None)
rain_source.head()
landcover = IO.Raster(os.path.join(data_path,'landcover.gz'))
landcover.mapshow()
plt.show()

ngpus = 1
#case_folder = os.path.join(os.getcwd(), 'flood_case') # define a case folder in the current directory
case_folder = 'C:\\Users\\weiyilan\\Desktop\\synx\\flood_case'
print(case_folder)
case_input = IO.InputModel(DEM, num_of_sections=ngpus, case_folder=case_folder)
..."

**Comment by weiyilan** [comment]
Thanks a lot! It worked.
